// ...existing code...
module.exports = {
  // ...existing code...
  theme: {
    extend: {
      colors: {
        primary: {
          50: '#f0f9ff',
          // ...existing code...
          500: '#0284c7', // Ensures 4.5:1 contrast on white
          600: '#0369a1', // Ensures 7:1 contrast on white
          // ...existing code...
          900: '#0c4a6e', // High contrast for accessibility
        },
        gray: {
          // ...existing code...
          700: '#374151', // Ensures 7:1 contrast on white 
          // ...existing code...
        }
        // ...existing code...
      },
      // ...existing code...
    },
  },
  plugins: [
    // ...existing code...
    require('@tailwindcss/forms')({
      strategy: 'class',
    }),
    // ...existing code...
  ],
};
